Upgrade macOS runners (#61)
After the runner update, the iOS Package step failed with errors like this:

```
error: Provisioning profile "Rectangles Development" doesn't include the currently selected device "iad20-fj924-670a3180-a8c5-4978-aedf-f3651d4a8a4b-EA3CA4056287" (identifier 0000FE00-0CCDEB2ED0E303D9). (in target 'Rectangles' from project 'Rectangles')
```

I suspect this is due to the new runner being an arm64 device so it's seeing the macOS machine as an iOS compatible device. So, force the generic build to prevent that error.